name: wallet_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI
  flutter_svg: ^1.1.6
  gap: ^3.0.0
  readmore: ^2.2.0
  google_fonts: ^5.0.0
  awesome_dialog: ^3.1.0
  flutter_spinkit: ^5.2.0
  curved_navigation_bar: ^1.0.3
  # dotted_line: ^3.1.0
  # image_picker: ^0.8.7+2
  # pull_to_refresh: ^2.0.0
  # dotted_border: ^2.0.0+3
  # salomon_bottom_bar: ^3.3.2
  # modal_bottom_sheet: ^2.1.2
  # syncfusion_flutter_sliders: ^21.1.38
  syncfusion_flutter_charts: ^23.1.40
  pie_chart: ^5.3.2
  dotted_border: ^2.1.0

  # Animations
  lottie: ^2.6.0
  shimmer: ^3.0.0
  flutter_bounce: ^1.1.0
  # auto_animated: ^3.1.0
  # flutter_animator: ^3.2.2
  # floating_action_bubble: ^1.1.4
  # loading_animation_widget: ^1.2.0+4

  # Helpers
  xml: ^6.0.0
  path: ^1.8.2
  intl: ^0.18.0
  local_auth: ^2.1.6
  url_launcher: ^6.1.9
  dropdown_search: ^3.0.1
  flutter_screenutil: ^5.6.1
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^5.4.1
  # meta: ^1.8.0
  # get_it: ^7.2.0
  # dartz: ^0.10.1
  # fluttertoast: ^8.2.1
  # path_provider: ^2.0.12
  # freezed_annotation: ^2.2.0
  # mask_text_input_formatter: ^2.4.0
  # flutter_rounded_date_picker: ^3.0.2

  # State management
  # provider: ^6.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  # get: ^4.6.5

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # shared_preferences: ^2.1.0
  # cached_network_image: ^3.2.3

  # Networking
  dio: ^5.1.1
  http: ^1.1.0
  html: ^0.15.3
  requests_inspector: ^2.3.5
  shared_preferences: ^2.2.0
  # retrofit: ^4.0.1
  # connectivity_plus: ^3.0.3

  # Models
  equatable: ^2.0.5

  # Localization
  easy_localization: ^3.0.2

  # Navigation
  go_router: ^10.0.0
  rive: ^0.11.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Samsung
      fonts:
        - asset: assets/fonts/samsung.ttf
